### PR TITLE
more community projects

### PR DESCRIPTION
**Pull request by myzie**

### CODE REVIEW

**Comment by myzie** [comment]
Linking to your projects in Risor. Thank you @applejag @mna.

**Comment by rubiojr** [comment]
@myzie if you feel there's a place under the risor-io org umbrella for awesome-risor, I'd be happy for that repo live here, and give you the control of its content.

**Comment by myzie** [comment]
@rubiojr, thanks for the offer - I think that'd be great. Sharing the management of it sounds good.

**Comment by rubiojr** [comment]
@myzie please feel free to copy the contents, I'll close mine once that's ready.

**Pull request merged**
