### PR TITLE
feat: allow excluding builtins

### PR DESCRIPTION
**Pull request by luisdavim**
relates to: #89

### CODE REVIEW

**Comment by myzie** [comment]
To fully remove the denied builtins, it seems like we need to have a mechanism to remove them from the Config `DefaultGlobals` and `Globals` maps. Including removing them from the Module objects stored there, for module-provided builtins.

(This is just based on a quick look, see also my comment [here](https://github.com/risor-io/risor/issues/89#issuecomment-1874812656))

**Comment by luisdavim** [comment]
OK, I'll have another look at this, thanks.

**Comment by luisdavim** [comment]
Updated the PR with another approach, overriding the `builtin` with one that always returns an error, this seems to work, at least for my use cases, let me know what you think.

**Comment by myzie** [comment]
@luisdavim - I riffed on what you were doing here:
https://github.com/risor-io/risor/pull/151/files

Would that way of doing it work for your purposes? If generally yes, we could add `WithGlobalOverride` to that if you still need it in addition to what I did there.

**Comment by luisdavim** [comment]
> @luisdavim - I riffed on what you were doing here:
> https://github.com/risor-io/risor/pull/151/files
> 
> Would that way of doing it work for your purposes? If generally yes, we could add `WithGlobalOverride` to that if you still need it in addition to what I did there.

I think the `WithGlobalOverride` will be useful to me as well, do you see anything wrong with my approach? Not sure why you opened that separate PR but I'll take a closer look and check the differences.

**Comment by luisdavim** [comment]
> > @luisdavim - I riffed on what you were doing here:
> > https://github.com/risor-io/risor/pull/151/files
> > 
> > Would that way of doing it work for your purposes? If generally yes, we could add `WithGlobalOverride` to that if you still need it in addition to what I did there.
> 
> I think the `WithGlobalOverride` will be useful to me as well, do you see anything wrong with my approach? Not sure why you opened that separate PR but I'll take a closer look and check the differences. 

OK, I see, I do like the support for nested modules 👍 but I do think `WithGlobalOverride` will be useful to me so if you could add it there, that would be great. Thanks.

**Comment by luisdavim** [comment]
closing in favour of #151.

**Pull request closed without merging**
