### PR TITLE
Enable `from xxx import xx as xx` statement in Risor

### PR DESCRIPTION
**Pull request by abadfox233**
This enhancement introduces support for the `from` and as `keywords` within the Risor compiler, extending its capabilities.

New Keywords: `FROM` and `AS`
* `Syntax Enhancement`: The `from` keyword now supports one or more identifiers after it, similar to `a.b.c`. Conversely, the `import` keyword can only be followed by a single identifier. The `as` keyword becomes optional when renaming statements.

Compiler Enhancement: New Opcode `FromImport`
* A new operation code (`FromImport`) has been added to the compiler section. This enables the recognition and execution of the enhanced import functionality.

Virtual Machine Implementation
* When executing the module import instruction in the virtual machine, the system attempts to import the specified module first. For instance, when encountering `from a.b.c import d`, the virtual machine attempts to import the `a.b.c.d` module.

Should the initial import fail, the system then tries to import variables within the module. For example, with `from a.b.c import d`, the virtual machine tries to import the `a.b.c` module and subsequently imports the global variable `d` from the `c` module.

Similar to Python, both imported modules and variables are set as **constants** after the import process.

This enhancement expands Risor's functionality to provide more flexible and comprehensive import statements, resembling Python's behavior while maintaining consistency within the Risor environment.

### CODE REVIEW

**Comment by myzie** [comment]
Thanks @abadfox233! This looks great at a glance. Will get hands on with it soon.

Did you come across any limitations or issues with the approach in your testing so far?

It would be good to add some unit tests as we get closer to merging this.

**Comment by abadfox233** [comment]
Thank you for your feedback! I've gone ahead and added some unit tests as suggested. These tests cover various scenarios and should help ensure the reliability of the code. If there are specific areas you'd like me to focus on or any further suggestions, please let me know. I'm committed to enhancing the quality of the codebase.

**Comment by myzie** [comment]
This is working well. One case we should consider is importing from built-in modules. We should probably make this work, for example:

```python
>>> from math import min
module not found: math
>>> math.min
builtin(min)
```

We could also add this in follow up work.

Otherwise this seems to match what you'd expect coming from Python, which is good.

**Review by myzie — APPROVED** [review]
Good work!

**Pull request merged**
